Import('*')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 1 - Proofs, Metric Spaces, Topology.pdf',
        source = '#src/lectures/lecture1.tex')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 2 - Sequences, Continuity.pdf',
        source = '#src/lectures/lecture2.tex')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 3 - Compactness, EVT, Correspondences.pdf',
        source = '#src/lectures/lecture3.tex')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 4 - Differentiation, IFT, Unconstrained Optimization.pdf',
        source = '#src/lectures/lecture4.tex')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 5 - Constrained Optimization, Envelope Theorem, Integration.pdf',
        source = '#src/lectures/lecture5.tex')

env.PDF(target = '#out/lectures/Math Camp 2022 Lecture 6 - Linear Algebra, ODE.pdf',
        source = '#src/lectures/lecture6.tex')

env.link(target = ['#docs/out/lectures/Math Camp 2022 Lecture 1 - Proofs, Metric Spaces, Topology.pdf'],
         source = ['#out/lectures/Math Camp 2022 Lecture 1 - Proofs, Metric Spaces, Topology.pdf'])

env.link(target = ['#docs/out/lectures/Math Camp 2022 Lecture 2 - Sequences, Continuity.pdf'],
         source = ['#out/lectures/Math Camp 2022 Lecture 2 - Sequences, Continuity.pdf'])

env.link(target = ['#docs/out/lectures/Math Camp 2022 Lecture 3 - Compactness, EVT, Correspondences.pdf'],
         source = ['#out/lectures/Math Camp 2022 Lecture 3 - Compactness, EVT, Correspondences.pdf'])

env.link(target = ['#docs/out/lectures/Math Camp 2022 Lecture 4 - Differentiation, IFT, Unconstrained Optimization.pdf'],
         source = ['#out/lectures/Math Camp 2022 Lecture 4 - Differentiation, IFT, Unconstrained Optimization.pdf'])

env.link(target = ['#docs/out/lectures/Math Camp 2022 Lecture 5 - Constrained Optimization, Envelope Theorem, Integration.pdf'],
         source = ['#out/lectures/Math Camp 2022 Lecture 5 - Constrained Optimization, Envelope Theorem, Integration.pdf'])
