Import('*')

env.PDF(target = '#out/syllabus/Math Camp 2023 Syllabus.pdf',
        source = '#src/syllabus/syllabus.tex')

env.link(target = ['#docs/out/syllabus/Math Camp 2023 Syllabus.pdf'],
         source = ['#out/syllabus/Math Camp 2023 Syllabus.pdf'])
